from datetime import datetime, timedelta, timezone

print(datetime.now())
print(datetime(2018, 9, 7, 14, 41, 37))
print(datetime.now().timestamp())
print(datetime.fromtimestamp(1536302626))
print(datetime.utcfromtimestamp(1536302626))
print(datetime.strptime('2018-09-07 14:47:05', '%Y-%m-%d %H:%M:%S'))
print(datetime.now().strftime('%a, %b %d %H:%M'))

dt = datetime.now()
print(dt)
print(dt + timedelta(hours=1))
print(dt + timedelta(days=2))
print(dt + timedelta(minutes=1))
print(dt + timedelta(days=1, hours=1, minutes=1))
print(dt, dt.tzinfo)
utc8 = timezone(timedelta(hours=8))
dt.replace(tzinfo=utc8)
print(dt, dt.tzinfo)

utc_dt = datetime.utcnow().replace(tzinfo=timezone.utc)
print(utc_dt)
bj_dt = utc_dt.astimezone(timezone(timedelta(hours=8)))
print(bj_dt)
ny_dt = utc_dt.astimezone(timezone(timedelta(hours=20)))
print(ny_dt)
ny_dt2 = bj_dt.astimezone(timezone(timedelta(hours=20)))
print(ny_dt2)
