d = {'Michael': 95, 'Bob': 75, 'Tracy': 85}
print(d['Bob'])
d['Adam'] = 67
print(d['Adam'])
print('Thomas' in d)
print(d.get('Adam'))
print(d.get('Thomas'))
print(d)
d.pop('Adam')
print(d)
print('----------')

s = set([1, 1, 2, 2, 3, 3])
print(s)
s.add(4)
s.add(4)
print(s)
s.pop()
print(s)
s.remove(4)
print(s)
s1 = set([1, 2, 3])
s2 = set([2, 3, 4])
print(s1 & s2)
print(s1 | s2)